/* AUTOGENERATED FILE — config values only, no secrets here */

// Load from Vite env vars (VITE_* prefix required for client-side exposure).
// If a var is missing we throw at startup to surface misconfiguration immediately
// rather than failing silently at runtime with cryptic network errors.

export const projectId = import.meta.env.VITE_SUPABASE_PROJECT_ID;
export const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
export const supabaseFunctionsBaseUrl = import.meta.env.VITE_SUPABASE_FUNCTIONS_BASE_URL;
export const publicAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;

const isMissingEnv = (v: unknown) => {
  if (typeof v !== "string") return true;
  const t = v.trim();
  return !t || t === "undefined" || t === "null";
};

if (
  isMissingEnv(projectId) ||
  isMissingEnv(supabaseUrl) ||
  isMissingEnv(supabaseFunctionsBaseUrl) ||
  isMissingEnv(publicAnonKey)
) {
  throw new Error(
    `[Piyupair] Missing environment variables. ` +
    `Ensure VITE_SUPABASE_PROJECT_ID, VITE_SUPABASE_URL, VITE_SUPABASE_FUNCTIONS_BASE_URL, and VITE_SUPABASE_ANON_KEY are set.`
  );
}